import Database from 'better-sqlite3';
import path from 'path';
import crypto from 'crypto';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dbPath = path.join(__dirname, '..', 'db.sqlite');
const db = new Database(dbPath);

const baseUrl = 'http://127.0.0.1:3001';
const projectId = '1782543650666';

async function apiRequest(endpoint, options = {}) {
  const res = await fetch(`${baseUrl}${endpoint}`, {
    ...options,
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data.error || `HTTP ${res.status}`);
    err.status = res.status;
    err.data = data;
    throw err;
  }
  return data;
}

async function waitForTaskTerminal(taskId, timeoutMs = 120000) {
  const started = Date.now();
  while (true) {
    const row = db.prepare("SELECT * FROM comfyui_tasks WHERE id = ?").get(taskId);
    if (!row) throw new Error(`Task ${taskId} not found in DB`);
    if (row.status === 'succeeded' || row.status === 'failed' || row.status === 'cancelled') {
      return row;
    }
    if (Date.now() - started > timeoutMs) {
      throw new Error(`Timeout waiting for task ${taskId}. Current status: ${row.status}`);
    }
    await new Promise(r => setTimeout(r, 1000));
  }
}

async function run() {
  const results = {};

  // Fetch project info
  const scripts = await apiRequest('/api/generated-scripts');
  const project = scripts.find(p => p.id === projectId);
  if (!project) throw new Error(`Project ${projectId} not found`);
  const shot = project.newShots[0];

  // ----------------------------------------------------
  // Test 1: 64-bit Seed Precision Test
  // ----------------------------------------------------
  console.log("\n--- Test 1: 64-bit Seed Precision Test ---");
  try {
    const bigSeed = "18446744073709551613";
    const res = await apiRequest('/api/generate-image', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        targetId: shot.id,
        targetType: 'shot',
        viewType: 'main',
        prompt: 'A beautiful starry night',
        seedMode: 'keep',
        seed: bigSeed,
        model: 'sd_xl_base_1.0.safetensors',
        platform: 'comfyui',
        skipTranslation: true
      })
    });
    
    const taskId = res.taskId;
    const taskRow = db.prepare("SELECT * FROM comfyui_tasks WHERE id = ?").get(taskId);
    
    const parsedWorkflow = JSON.parse(taskRow.apiWorkflowJson);
    const ksamplerSeed = parsedWorkflow['5'].inputs.seed;
    
    console.log(`Task ID: ${taskId}`);
    console.log(`SQLite seed field: ${taskRow.seed} (Type: ${typeof taskRow.seed})`);
    console.log(`KSampler seed value: ${ksamplerSeed} (Type: ${typeof ksamplerSeed})`);
    
    const matchesExactly = (taskRow.seed === bigSeed) && (ksamplerSeed === bigSeed) && (typeof ksamplerSeed === 'string');
    
    const finalTask = await waitForTaskTerminal(taskId);
    console.log(`Final Task Status: ${finalTask.status}`);
    
    const t1Passed = matchesExactly && finalTask.status === 'succeeded';
    results.test1 = {
      status: t1Passed ? 'PASS' : 'FAIL',
      taskId,
      dbSeed: taskRow.seed,
      wfSeed: ksamplerSeed,
      wfSeedType: typeof ksamplerSeed,
      finalStatus: finalTask.status,
      conclusion: t1Passed
        ? "PASS: 64-bit seed saved without precision loss and successfully generated by ComfyUI."
        : "FAIL: Seed mismatch, type incorrect, or task failed."
    };
  } catch (err) {
    console.error("Test 1 failed:", err);
    results.test1 = { status: 'FAIL', error: err.message };
  }

  // ----------------------------------------------------
  // Test 2: Custom workflow node mapping test
  // ----------------------------------------------------
  console.log("\n--- Test 2: Custom workflow node mapping test ---");
  const mockWfPath = path.join(__dirname, '..', 'mock_custom_workflow.json');
  try {
    const mockWorkflow = {
      "1": { "class_type": "CheckpointLoaderSimple", "inputs": { "ckpt_name": "sd_xl_base_1.0.safetensors" } },
      "10": { "class_type": "CLIPTextEncode", "inputs": { "text": "positive 1" } },
      "11": { "class_type": "CLIPTextEncode", "inputs": { "text": "positive 2" } },
      "20": { "class_type": "KSampler", "inputs": { "seed": 0 } },
      "21": { "class_type": "KSampler", "inputs": { "seed": 0 } }
    };
    fs.writeFileSync(mockWfPath, JSON.stringify(mockWorkflow, null, 2));
    
    function localFindComfyNode(workflow, envName, classTypes, titlePattern, envOverrides = {}) {
      const configured = envOverrides[envName];
      if (configured) {
        if (!workflow[configured]) throw new Error(`${envName} points to missing ComfyUI node ${configured}`);
        return configured;
      }
      const matches = Object.entries(workflow).filter(([, node]) => classTypes.includes(node.class_type));
      if (titlePattern) {
        const titled = matches.find(([, node]) => titlePattern.test(node._meta?.title || ''));
        if (titled) return titled[0];
      }
      return undefined;
    }
    
    // Test Scenario A: No mapping
    const promptNodeA = localFindComfyNode(mockWorkflow, 'COMFYUI_PROMPT_NODE_ID', ['CLIPTextEncode'], /story[_ -]?prompt|positive/i, {});
    const seedNodeA = localFindComfyNode(mockWorkflow, 'COMFYUI_SEED_NODE_ID', ['KSampler', 'KSamplerAdvanced', 'RandomNoise', 'Seed'], /seed|sampler/i, {});
    
    console.log(`Scenario A (No mapping ID / No matching titles):`);
    console.log(`- Mapped Prompt Node: ${promptNodeA} (Expected: undefined)`);
    console.log(`- Mapped Seed Node: ${seedNodeA} (Expected: undefined)`);
    
    // Test Scenario B: Explicit mapping configured
    const envOverrides = {
      COMFYUI_PROMPT_NODE_ID: '10',
      COMFYUI_SEED_NODE_ID: '20'
    };
    const promptNodeB = localFindComfyNode(mockWorkflow, 'COMFYUI_PROMPT_NODE_ID', ['CLIPTextEncode'], /story[_ -]?prompt|positive/i, envOverrides);
    const seedNodeB = localFindComfyNode(mockWorkflow, 'COMFYUI_SEED_NODE_ID', ['KSampler', 'KSamplerAdvanced', 'RandomNoise', 'Seed'], /seed|sampler/i, envOverrides);
    
    console.log(`Scenario B (Explicit environment overrides: Prompt=10, Seed=20):`);
    console.log(`- Mapped Prompt Node: ${promptNodeB} (Expected: 10)`);
    console.log(`- Mapped Seed Node: ${seedNodeB} (Expected: 20)`);
    
    const t2Passed = (promptNodeA === undefined) && (seedNodeA === undefined) &&
                     (promptNodeB === '10') && (seedNodeB === '20');
                     
    results.test2 = {
      status: t2Passed ? 'PASS' : 'FAIL',
      promptNodeA,
      seedNodeA,
      promptNodeB,
      seedNodeB,
      conclusion: t2Passed
        ? "PASS: Custom workflow correctly disables inputs under ambiguity and enables them with explicit node ID mappings."
        : "FAIL: Node mapping resolution logic is incorrect."
    };
  } catch (err) {
    console.error("Test 2 failed:", err);
    results.test2 = { status: 'FAIL', error: err.message };
  } finally {
    if (fs.existsSync(mockWfPath)) fs.unlinkSync(mockWfPath);
  }

  // ----------------------------------------------------
  // Test 3: Generation failure retains old image test
  // ----------------------------------------------------
  console.log("\n--- Test 3: Generation failure retains old image test ---");
  try {
    const oldImgUrl = "/uploads/projects/1782543650666/shots/01/mock_success.png";
    db.prepare(`
      INSERT OR REPLACE INTO comfyui_tasks (
        id, projectId, targetId, targetType, viewType, status, prompt, negativePrompt, seed, model, width, height, createdAt, updatedAt
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      "test_fail_task_old",
      projectId,
      shot.id,
      'shot',
      'main',
      'succeeded',
      'starry sky',
      'bad',
      '12345',
      'sd_xl_base_1.0.safetensors',
      768,
      512,
      new Date(Date.now() - 20000).toISOString(),
      new Date(Date.now() - 20000).toISOString()
    );

    const row = db.prepare('SELECT value FROM store WHERE key = ?').get('generated_scripts');
    const scriptsList = JSON.parse(row.value);
    const pIdx = scriptsList.findIndex(p => p.id === projectId);
    let originalScriptUrl = "";
    if (pIdx !== -1) {
      originalScriptUrl = scriptsList[pIdx].newShots[0].generatedImageUrl || "";
      scriptsList[pIdx].newShots[0].generatedImageUrl = oldImgUrl;
      db.prepare('INSERT OR REPLACE INTO store (key, value) VALUES (?, ?)').run('generated_scripts', JSON.stringify(scriptsList));
    }
    
    console.log(`Original image URL set to: ${oldImgUrl}`);

    const res = await apiRequest('/api/generate-image', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        targetId: shot.id,
        targetType: 'shot',
        viewType: 'main',
        prompt: 'Task to fail in ComfyUI',
        seedMode: 'random',
        model: 'sd_xl_base_1.0.safetensors',
        platform: 'comfyui',
        skipTranslation: true
      })
    });
    
    const failTaskId = res.taskId;
    console.log(`Submitted failing task. ID: ${failTaskId}`);
    
    db.prepare("UPDATE comfyui_tasks SET apiWorkflowJson = '{\"invalid\": true}' WHERE id = ?").run(failTaskId);
    console.log("Corrupted workflow in SQLite DB to force worker failure.");
    
    const failedTask = await waitForTaskTerminal(failTaskId);
    console.log(`Failed Task Status: ${failedTask.status}, Error: ${failedTask.error}`);
    
    const refreshedScripts = await apiRequest('/api/generated-scripts');
    const refreshedProject = refreshedScripts.find(p => p.id === projectId);
    const refreshedImgUrl = refreshedProject.newShots[0].generatedImageUrl;
    console.log(`refreshedImgUrl after failure: ${refreshedImgUrl}`);
    
    // Restore original image URL in SQLite store
    if (pIdx !== -1) {
      const refreshedRow = db.prepare('SELECT value FROM store WHERE key = ?').get('generated_scripts');
      const refreshedList = JSON.parse(refreshedRow.value);
      refreshedList[pIdx].newShots[0].generatedImageUrl = originalScriptUrl;
      db.prepare('INSERT OR REPLACE INTO store (key, value) VALUES (?, ?)').run('generated_scripts', JSON.stringify(refreshedList));
    }

    const t3Passed = (failedTask.status === 'failed') && (refreshedImgUrl === oldImgUrl);
    results.test3 = {
      status: t3Passed ? 'PASS' : 'FAIL',
      oldImgUrl,
      failTaskId,
      refreshedImgUrl,
      taskStatus: failedTask.status,
      conclusion: t3Passed
        ? "PASS: Generation failure correctly retained the old successful image URL and did not clear or overwrite it."
        : "FAIL: Image URL was cleared, modified, or task did not fail."
    };
  } catch (err) {
    console.error("Test 3 failed:", err);
    results.test3 = { status: 'FAIL', error: err.message };
  }

  // ----------------------------------------------------
  // Test 4: Model Freeze Test
  // ----------------------------------------------------
  console.log("\n--- Test 4: Model Freeze Test ---");
  try {
    const modelA = 'sd_xl_base_1.0.safetensors';
    const res = await apiRequest('/api/generate-image', {
      method: 'POST',
      body: JSON.stringify({
        projectId,
        targetId: shot.id,
        targetType: 'shot',
        viewType: 'main',
        prompt: 'A model freeze test',
        seedMode: 'random',
        model: modelA,
        platform: 'comfyui',
        skipTranslation: true
      })
    });
    const taskId = res.taskId;
    
    const enqueuedTask = db.prepare("SELECT * FROM comfyui_tasks WHERE id = ?").get(taskId);
    const apiWf = JSON.parse(enqueuedTask.apiWorkflowJson);
    const enqueuedWfModel = apiWf['1'].inputs.ckpt_name;
    
    console.log(`Enqueued Task ID: ${taskId}`);
    console.log(`Enqueued Model in SQLite: ${enqueuedTask.model}`);
    console.log(`Enqueued Model in apiWorkflowJson: ${enqueuedWfModel}`);
    
    const finalTask = await waitForTaskTerminal(taskId);
    console.log(`Final Task Status: ${finalTask.status}, Model: ${finalTask.model}`);
    
    const t4Passed = (enqueuedTask.model === modelA) && (enqueuedWfModel === modelA) && (finalTask.status === 'succeeded');
    results.test4 = {
      status: t4Passed ? 'PASS' : 'FAIL',
      taskId,
      enqueuedModel: enqueuedTask.model,
      wfModel: enqueuedWfModel,
      finalStatus: finalTask.status,
      conclusion: t4Passed
        ? "PASS: Model remains frozen to the enqueued Model A and is submitted directly to ComfyUI."
        : "FAIL: Model was updated or task failed."
    };
  } catch (err) {
    console.error("Test 4 failed:", err);
    results.test4 = { status: 'FAIL', error: err.message };
  }

  // ----------------------------------------------------
  // Summary
  // ----------------------------------------------------
  console.log("\n=== Final Test Results Summary ===");
  console.log(JSON.stringify(results, null, 2));
  
  const allPassed = Object.values(results).every(r => r.status === 'PASS');
  if (allPassed) {
    console.log("\nALL TESTS PASSED!");
    process.exit(0);
  } else {
    console.error("\nONE OR MORE TESTS FAILED!");
    process.exit(1);
  }
}

run();
